"""Create sentiment_analysis table

Revision ID: b6c95c2dd942
Revises: d1a2178f96c6
Create Date: 2025-02-12 04:04:21.140827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6c95c2dd942'
down_revision: Union[str, None] = 'd1a2178f96c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analysis', sa.Column('confidence', sa.Float(), nullable=False))
    
    # Convert 'created_at' to a Unix timestamp (BIGINT)
    op.alter_column('sentiment_analysis', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.BigInteger(),
                    nullable=False,
                    postgresql_using="EXTRACT(epoch FROM created_at)::bigint")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentiment_analysis', 'created_at',
                    existing_type=sa.Integer(),
                    type_=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_column('sentiment_analysis', 'confidence')
    # ### end Alembic commands ###
